### ISSUE TITLE
Notes Deletion

### ISSUE THREAD

**Issue by dukehm** [dtowell/contest-host#5] opened 2020-03-04 22:11 UTC
**Description**
Once a note has been added to the database, it cannot be deleted with button functionality on the edit_notes.php page.

**Reproduction  Steps**
1. Go to localhost:8000/edit_notes.php
2. Fill out information for adding a note in the new link and click the submit button.
3. Refresh page and then attempt to delete the note.
4. The note remains on page.

**Expected Behavior**
The expected behavior would be that the note would be deleted from the database and not be on the edit_notes.php or the announcements section on view_problems.php.

**Desktop**
 - OS: Windows 10
 - Browser: Chrome

**Comment by dtowell** [comment] 2020-03-04 22:48
this is a duplicate of bug #4

**Closed as completed by dtowell** 2020-03-04 22:48 UTC
