### ISSUE TITLE
Judge Functionality works for Teams. 

### ISSUE THREAD

**Issue by JohnH-312** [dtowell/contest-host#3] opened 2020-03-04 05:32 UTC
When logged into an account which is not marked as a judge, judge menu and judge specific pages are still accessible. 

**To Reproduce**
1. Go to edit contestants, create a new team without clicking the judge option
2. delete cookies, the click on view problems to access the login page
3. log in to the account you created
4. view and access the judge menu and pages

**Expected behavior**
When logged in as a User/Team which is NOT marked as a Judge, the Judge menu and websites associated with it, such as edit problems, should NOT be accessible. 

**Desktop:**
 - OS: Ubuntu 19.0.4
 - Browser: chrome
 - Version newest

**Comment by dtowell** [comment] 2020-03-04 15:37
Cannot reproduce. Maybe have been fixed with #2

**Closed as completed by dtowell** 2020-03-04 15:37 UTC
